image: alpine/edge
packages:
  - go
  - golangci-lint
sources:
  - https://github.com/go-ap/storage-badger
secrets:
  - 4f33a026-5601-4174-939c-f57f9d871184
environment:
  GO111MODULE: 'on'
tasks:
  - fmt: |
      cd storage-badger
      test -z $(gofmt -l .)
  - tests: |
      cd storage-badger
      make test
  - coverage: |
      cd storage-badger
      git switch -C master origin/master
      make coverage
      go tool goveralls -flagname unit-tests -service=${CI_NAME} -coverprofile storage-badger.coverprofile -repotokenfile ~/.coveralls.tok
  - lint: |
      cd storage-badger
      golangci-lint run || true
