image: alpine/edge
packages:
  - go
sources:
  - https://github.com/go-ap/storage-badger
secrets:
  - 4f33a026-5601-4174-939c-f57f9d871184
environment:
  GO111MODULE: 'on'
tasks:
  - tests: |
      cd storage-badger
      make test
  - coverage: |
      cd storage-badger
      git switch -C master origin/master
      make coverage
      go run github.com/mattn/goveralls@latest -flagname unit-tests -service=${CI_NAME} -coverprofile storage-badger.coverprofile -repotokenfile ~/.coveralls.tok
